[phases.build]
cmds = ["bash build.sh"]

[phases.install]
cmds = ["mvn dependency:go-offline"]

[start]
cmd = "java -Xms256m -Xmx512m -Dserver.address=0.0.0.0 -Dspring.profiles.active=railway -Djava.awt.headless=true -jar target/*.jar"
